server:
  port: 8082

application:
  name: Hadef
  url: www.hopenshare.com
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  show-actuator: true
management:
  server:
    port: 9090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
