package com.learning.hadef.domain.value;

import lombok.Getter;

@Getter
public enum FailureEnum {
    STUDENT_NOT_FOUND(1),
    FAILED_TO_SIGNUP_STUDENT(2),
    FAILED_TO_LOGIN_STUDENT(3),
    FAILED_TO_CREATE_STUDENT(4),
    TEACHER_NOT_FOUND(5),
    FAILED_TO_SIGNUP_TEACHER(6),
    FAILED_TO_LOGIN_TEACHER(7),
    FAILED_TO_CREATE_TEACHER(8),
    COURSE_NOT_FOUND(10),
    FAILED_TO_CREATE_COURSE(1001),
    FAILED_TO_CREATE_COURSE_DUE_TO_DUPLICATE_SLUG_TITLE(1002),
    ERROR_IN_COURSE_ID(1003),
    ERROR_IN_COURSE_SLUG_TITLE(1004),
    FAILED_IN_UPDATE_COURSE(1005),
    FAILED_TO_CREATE_COURSE_SUBJECT(2001),
    FAILED_TO_CREATE_COURSE_SUBJECT_DUE_TO_DUPLICATE_CODE(2002),
    ERROR_IN_COURSE_SUBJECT_ID(2003),
    ERROR_IN_COURSE_SUBJECT_CODE(2004),
    FAILED_IN_UPDATE_COURSE_SUBJECT(2005);

    private final int code;

    FailureEnum(int code) {
        this.code = code;
    }
}
